---
title: The Use of GenAI in Supporting Student Design Learning
author: nernst
---

# The Use of GenAI in Supporting Student Design Learning

## Study Motivation
- software engineers are rapidly adopting generative AI (Stack Overflow Survey, 2025), and AI appears to increase developer productivity (Bird et al., 2022; Cui et al., 2024).
- however, no one knows how much it helps with software design questions (Guerra and Ernst, 2025).
- it is also not known how AI can be used to help students learn software design and implementation.
  - if it should be used, which techniques effectively support students?

## Open Questions
1. how do students leverage AI tools in design tasks?
2. how does AI influence team dynamics? 
3. how is AI changing software practices? 

## Why now? 

- you are among the first generations of students who have access to these tools while learning software design.
- future employers will expect you to use generative AI for software development; we want to discover how to teach these skills effectively.

## Possible Outcomes
- strategies for using generative AI in software design.
- educational methods to teach students how to use generative AI effectively.


## Consent

A researcher in a different lab, Jay, will now walk through the consent process with you and collect signed forms. She will hold onto the forms until after finalization of the course grades. 

There is no way your choice to participate influences your course grade, the teaching team will not know whether you have consented until *after* I submit the final marks. 

## Consent
- consent should be free and informed - please read the form carefully.
- consent may be withdrawn at any time by emailing Jay directly. 
- the study protocol has been approved by the University Human Research Ethics board

## Things to Know
- we will study the coursework you submit, this includes chat logs, reflections, and the software system you designed.
- this data will be anonymized before we look at it - removing names and other identifying info
- the data are stored in Canada in a secure cloud repository

## Risks
We don't believe there are any risks to participating in the research.

There are no additional tasks to conduct beyond the ones already included in the course itself.

## Dissemination
- we hope to use the results of the research in publications and dissertations.
- if you fill-out your e-mail address on the consent for we will send you a summary of the results. 
- a subset of anonymized data may be shared in research archives.

## Questions? 